### ISSUE TITLE
Specify .babelrc

### ISSUE THREAD

**Issue by kyleholzinger** [babel/gulp-babel#127] opened 2017-09-26 15:18 UTC
Can you specify your own `.babelrc` file? I want to have a different preset in development vs in production. (I develop in chrome, but I need to be able to target back to IE11)

**Comment by ben-z** [comment] 2017-12-16 03:46
I think this is a duplicate of #48.

**Comment by iDVB** [comment] 2018-02-07 16:37
@Sawtaytoes why is there an issue that says it does? 
https://github.com/babel/gulp-babel/issues/48

**Comment by hzoo** [comment] 2018-03-19 19:08
Not sure what this is asking for, gulp-babel will read the babelrc in your project yes.

**Closed by hzoo** 2018-03-19 19:08 UTC

**Comment by kyleholzinger** [comment] 2018-03-19 19:11
Wasn't aware of the `env` config flag. Thank you very much @hzoo !
